### ISSUE TITLE
Trying to use your drupal7 nginx php-fpm and getting a nginx error

### ISSUE THREAD

**Issue by dubcanada** [that0n3guy/docker#1]
Hello

I am trying to use your Drupal 7 dokku base and I keep getting an nginx error on start

**\* Running /etc/my_init.d/00_configure_nginx.sh...
sed: can't read /etc/nginx/sites-enabled/default: No such file or directory
/etc/my_init.d/00_configure_nginx.sh: 14: [: -eq: unexpected operator

Any idea of what is up?

**Comment by that0n3guy** [comment]
I have those errors as well as it turns out... but doesn't cause any issues.  

I just pushed a change.  I've not tested if it fixes it, but it should.

**Comment by dubcanada** [comment]
I'm trying to figure out why default would be missing, I thought that came with the default nginx install.

**Comment by dubcanada** [comment]
Unless https://github.com/that0n3guy/docker/blob/master/baseimage-nginx-phpfpm/nginx/setup.sh#L3 doesn't get ran...

Anyways I'll check out the new build when it is up in the registrary.

**Comment by that0n3guy** [comment]
In the drupal7 build... its different.  It gets rid of the default nginx configs completely (https://github.com/that0n3guy/docker/blob/master/baseimage-nginx-phpfpm-drupal7/Dockerfile#L8) and uses https://github.com/perusio/drupal-with-nginx.

**Comment by dubcanada** [comment]
Now I am getting an error

https://github.com/that0n3guy/docker/blob/master/baseimage-nginx-phpfpm/nginx/init.sh#L17

/etc/my_init.d/00_configure_nginx.sh: 17: [: -eq: unexpected operator

**Comment by dubcanada** [comment]
Just need to add a check around that line

```
if [ -n "$SYNC_UID" ]; then
    if [ $SYNC_UID -eq 1 ]; then
        ...
    fi
fi
```

**Comment by that0n3guy** [comment]
my bad... this is set.  I pushed it.
